### ISSUE TITLE
Error: "Unable to find component sensor.trakt"

### ISSUE THREAD

**Issue by fredrikbaberg** [custom-components/sensor.trakt#2]
After adding `trakt.py` to `custom_components/sensor/` and restarting I get "Unable to find component sensor.trakt".
With more detailed logging, I get:
```
Error loading custom_components.sensor.trakt. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/loader.py", line 94, in get_component
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/sensor/trakt.py", line 12, in <module>
    import trakt
ModuleNotFoundError: No module named 'trakt'
```

This is on a "Virtual server" install of Hass.io, Home Assistant 0.78.3

**Comment by iantrich** [comment]
Very strange. `trakt` is listed as a dependency and should be loaded on restart. I don't have my instance up right now, but there is an add-on for Hass.io that allows you to install dependencies manually, Custom Dependencies

https://github.com/home-assistant/hassio-addons/tree/master/custom_deps

**Comment by ludeeus** [comment]
`ModuleNotFoundError: No module named 'trakt'` are very normal for custom_components.
A restart usually corrects that.

**Comment by fredrikbaberg** [comment]
> `ModuleNotFoundError: No module named 'xxxxx'` are very normal for custom_components.
> A restart usually corrects that.

I tried multiple restarts (both of only Home Assistant and of the machine itself) without success.

**Comment by fredrikbaberg** [comment]
> Very strange. `trakt` is listed as a dependency and should be loaded on restart. I don't have my instance up right now, but there is an add-on for Hass.io that allows you to install dependencies manually, Custom Dependencies
> 
> https://github.com/home-assistant/hassio-addons/tree/master/custom_deps

Thank you. I tried that, and now it works.
