### ISSUE TITLE
Issue causing fatal error

### ISSUE THREAD

**Issue by davericher** [custom-components/sensor.trakt#27]
Fatal issue causing HomeAssistant to close. Can confirm the OAuth tokens are fine

ha - 0.96.2
hacs - 0.12.1
trakt - 1.0.1

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner


    self.run()


  File "/usr/local/lib/python3.7/threading.py", line 870, in run


    self._target(*self._args, **self._kwargs)


  File "/usr/src/app/homeassistant/util/logging.py", line 88, in _process


    self._queue.get(), self.loop).result()


  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 430, in result


    self._condition.wait(timeout)


concurrent.futures._base.CancelledError




Traceback (most recent call last):


  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main


    "__main__", mod_spec)


  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code


    exec(code, run_globals)


  File "/usr/src/app/homeassistant/__main__.py", line 404, in <module>


    sys.exit(main())


  File "/usr/src/app/homeassistant/__main__.py", line 396, in main


    exit_code = asyncio_run(setup_and_run_hass(config_dir, args))


  File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run


    return loop.run_until_complete(main)


  File "uvloop/loop.pyx", line 1445, in uvloop.loop.Loop.run_until_complete


  File "uvloop/loop.pyx", line 1438, in uvloop.loop.Loop.run_until_complete


  File "uvloop/loop.pyx", line 1347, in uvloop.loop.Loop.run_forever


  File "uvloop/loop.pyx", line 487, in uvloop.loop.Loop._run


  File "uvloop/loop.pyx", line 404, in uvloop.loop.Loop._on_idle


  File "uvloop/cbhandles.pyx", line 68, in uvloop.loop.Handle._run


  File "/usr/src/app/homeassistant/helpers/entity_component.py", line 221, in _async_setup_platform


    await self._platforms[key].async_setup(platform_config, discovery_info)


  File "/usr/src/app/homeassistant/helpers/entity_platform.py", line 90, in async_setup


    await self._async_setup_platform(async_create_setup_task)


  File "/usr/src/app/homeassistant/helpers/entity_platform.py", line 126, in _async_setup_platform


    SLOW_SETUP_MAX_WAIT)


  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for


    return fut.result()


  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run


    result = self.fn(*self.args, **self.kwargs)


  File "/config/custom_components/trakt/sensor.py", line 81, in setup_platform


    continue_setup_platform(hass, config, token, add_devices, discovery_info)


  File "/config/custom_components/trakt/sensor.py", line 89, in continue_setup_platform


    add_devices([TraktUpcomingCalendarSensor(hass, config, token)], True)


  File "/config/custom_components/trakt/sensor.py", line 127, in __init__


    self.update()


  File "/config/custom_components/trakt/sensor.py", line 144, in update


    calendar = MyShowCalendar(days=self._days)


  File "/usr/local/lib/python3.7/site-packages/trakt/calendar.py", line 31, in __init__


    self._get()


  File "/usr/local/lib/python3.7/site-packages/trakt/core.py", line 455, in inner


    json_data = self._handle_request('get', url)


  File "/usr/local/lib/python3.7/site-packages/trakt/core.py", line 432, in _handle_request


    raise self.error_map[response.status_code]()


trakt.errors.OAuthException: Unauthorized - OAuth must be provided

```

**Comment by iantrich** [comment]
Try deleting the conf file and restarting

**Comment by davericher** [comment]
Same failure

**Comment by iantrich** [comment]
What's your redirect URI?

**Comment by davericher** [comment]
Your update did fix it
