### ISSUE TITLE
ModuleNotFoundError: No module named 'requests_oauthlib'

### ISSUE THREAD

**Issue by hardtekpt** [custom-components/sensor.trakt#28]
After installing this component I keep getting this error, even after restarting home assistant like recommended in the readme file.

`2019-08-02 14:01:09 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up platform trakt
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 126, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/trakt/sensor.py", line 79, in setup_platform
    request_app_setup(hass, config, add_devices, discovery_info)
  File "/home/homeassistant/.homeassistant/custom_components/trakt/sensor.py", line 46, in request_app_setup
    from requests_oauthlib import OAuth2Session
ModuleNotFoundError: No module named 'requests_oauthlib'`

I've tried to manually install the module with pip3 with no success.

**Comment by iantrich** [comment]
HA version?

**Comment by hardtekpt** [comment]
HA version 0.96.0
on raspi 3B running raspbian buster

**Comment by iantrich** [comment]
Odd, I'm on 0.96 as well with no issues. The manifest.json file should handle dependency installation. Have you tried restarting more than once?

**Comment by hardtekpt** [comment]
My bed, I wasn't aware of this manifest.json file, I thought I only needed the sensor.py file, as soon as I included the manifest.json and restored HA it installed the module and is now working correctly. Thanks!!

**Comment by iantrich** [comment]
Everything in the folder should be copied
