### ISSUE TITLE
module trakt has no attribute 'core'

### ISSUE THREAD

**Issue by solo1988** [custom-components/sensor.trakt#31]
It happens when i send pin code

module 'trakt' has no attribute 'core'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 134, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1226, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1251, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/components/configurator/__init__.py", line 235, in async_handle_service_call
    await self.hass.async_add_job(callback, call.data.get(ATTR_FIELDS, {}))
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/trakt/sensor.py", line 57, in trakt_configuration_callback
    continue_setup_platform(hass, config, token, add_devices, discovery_info)
  File "/config/custom_components/trakt/sensor.py", line 89, in continue_setup_platform
    add_devices([TraktUpcomingCalendarSensor(hass, config, token)], True)
  File "/config/custom_components/trakt/sensor.py", line 118, in __init__
    trakt.core.OAUTH_TOKEN = token
AttributeError: module 'trakt' has no attribute 'core'

**Comment by engrbm87** [comment]
Updating to the latest version allows configuring the component using the UI without requiring pin code.
