### ISSUE TITLE
When you change the number of "Days to look forward for movies and shows" parameter it crashes the HomeAssistant Front End

### ISSUE THREAD

**Issue by jayscovill** [custom-components/sensor.trakt#41]
## Version of Home Assistant
.108.6

## Version of the custom_component
2.0.0

## Describe the bug
When you change the number of "Days to look forward for movies and shows" parameter it crashes the HomeAssistant Front End

## Debug log

```
2020-05-03 16:07:33 ERROR (Thread-17) [pychromecast.controllers] Exception thrown when calling cast status listener
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pychromecast/socket_client.py", line 1180, in _report_status
    listener.new_cast_status(self.status)
  File "/usr/src/homeassistant/homeassistant/components/cast/helpers.py", line 161, in new_cast_status
    self._cast_device.new_cast_status(cast_status)
  File "/usr/src/homeassistant/homeassistant/components/cast/media_player.py", line 487, in new_cast_status
    self.schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 430, in schedule_update_ha_state
    self.hass.add_job(self.async_update_ha_state(force_refresh))
  File "/usr/src/homeassistant/homeassistant/core.py", line 285, in add_job
    self.loop.call_soon_threadsafe(self.async_add_job, target, *args)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 736, in call_soon_threadsafe
    self._check_closed()
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 479, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
root@hassio:/usr/share/hassio/homeassistant#  
```

**Comment by engrbm87** [comment]
Closing this issue as the logs are related to the cast media_player component.
